import turtle
screen=turtle.Screen()
pen=turtle.Turtle()
pen.width(20)
turtle.speed(1)
turtle.fillcolor('red')
turtle.fillcolor('cyan')
turtle.begin_fill()
pen=turtle.Turtle()
pen.color('red')
screen.bgcolor('yellow')
turtle.forward(50)
turtle.right(90)
turtle.forward(100)
turtle.right(90)
turtle.forward(100)
turtle.right(90)
turtle.forward(100)
turtle.right(90)
turtle.forward(50)
turtle.end_fill()


turtle.done()